name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      env:
        ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        sudo apt update
        sudo apt install -y \
        libpq-dev libxml2-dev libxslt1-dev file git-core g++ libprotobuf-dev protobuf-compiler pkg-config nodejs gcc autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev yarn libidn11-dev libicu-dev libjemalloc-dev
        echo ${ENV_PRODUCTION} > .env.production
        gem update --system
        gem install bundler --no-document
        bundle install \
          -j$(getconf _NPROCESSORS_ONLN) \
          --deployment --without development test
        RAILS_ENV=production bundle exec rails assets:precompile
