name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Initial setup
      env:
        ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo ${ENV_PRODUCTION} > .env.production
        ls
    - name: Docker build & run
      run: |
        docker-compose run --rm web rake 
    - name: Rails exec command
      run: docker-compose run --rm web rails assets:precompile
    - name: Check actions directory
      run: echo 'Curennt directory' && ls && echo 'public directory' && ls public
